document.addEventListener('DOMContentLoaded', ()=>{
  const y=document.getElementById('year'); if(y) y.textContent=new Date().getFullYear();
  document.querySelectorAll('[data-toggle-theme]').forEach(b=>b.addEventListener('click', ()=> document.body.classList.toggle('dark')));
  const type = document.body.getAttribute('data-type') || '';
  if(type==='fitness'){ const bmiBtn=document.getElementById('bmiCalc'); if(bmiBtn) bmiBtn.addEventListener('click', ()=>{ const w=parseFloat(document.getElementById('bmiWeight').value); const h=parseFloat(document.getElementById('bmiHeight').value)/100; if(!w||!h){ alert('Uzupełnij dane'); return; } const bmi=(w/(h*h)).toFixed(1); document.getElementById('bmiResult').textContent='Twoje BMI: '+bmi; }); const form=document.getElementById('fitforgeBooking'); if(form) form.addEventListener('submit', e=>{ e.preventDefault(); document.getElementById('bookingMsg').textContent='Rezerwacja przyjęta (symulacja).'; form.reset(); }); const g=document.getElementById('fitGallery'); if(g){ for(let i=1;i<=6;i++){ const img=document.createElement('img'); img.src=`https://picsum.photos/seed/fit${i}/400/260`; g.appendChild(img);} } }
  if(type==='law'){ const f=document.getElementById('lexFaq'); if(f){ ['Jak umówić konsultację?','Ile kosztuje porada?','Czas trwania sprawy?'].forEach(q=>{ const d=document.createElement('div'); d.className='card'; d.innerHTML=`<strong>${q}</strong><p class='muted'>Przykładowa odpowiedź (symulacja).</p>`; f.appendChild(d); }); } const form=document.getElementById('lexContact'); if(form) form.addEventListener('submit', e=>{ e.preventDefault(); document.getElementById('lexMsg').textContent='Wiadomość wysłana (symulacja).'; form.reset(); }); }
  if(type==='restaurant'){ const menuList=document.getElementById('menuList'); if(menuList){ const menu=[{name:'Smoothie Bowl',cat:'śniadanie'},{name:'Burgery z soczewicy',cat:'obiad'},{name:'Brownie',cat:'deser'}]; const render=(term)=>{ menuList.innerHTML=''; menu.filter(i=>!term||i.name.toLowerCase().includes(term.toLowerCase())||i.cat.includes(term.toLowerCase())).forEach(it=>{ const d=document.createElement('div'); d.className='card'; d.innerHTML=`<h4>${it.name}</h4><p class='muted'>${it.cat}</p>`; menuList.appendChild(d); }); }; render(''); document.getElementById('menuFilter').addEventListener('input', e=>render(e.target.value)); const form=document.getElementById('greenBooking'); if(form) form.addEventListener('submit', e=>{ e.preventDefault(); document.getElementById('greenMsg').textContent='Rezerwacja przyjęta.'; form.reset(); }); } }
  if(type==='realestate'){ const listings=document.getElementById('listings'); if(listings){ const data=[{title:'Mieszkanie 2 pokoje',price:350000,rooms:2,seed:'apt1'},{title:'Dom 4 pokoje',price:750000,rooms:4,seed:'home1'}]; const render=()=>{ listings.innerHTML=''; const max=parseInt(document.getElementById('priceMax').value||99999999,10); const rooms=parseInt(document.getElementById('roomsMin').value||1,10); data.filter(d=>d.price<=max&&d.rooms>=rooms).forEach(it=>{ const c=document.createElement('div'); c.className='card'; c.innerHTML=`<img src='https://picsum.photos/seed/${it.seed}/800/420' alt=''><h4>${it.title}</h4><p class='muted'>${it.rooms} pokoje — ${it.price.toLocaleString()} PLN</p>`; listings.appendChild(c); }); }; document.getElementById('applyFilter').addEventListener('click', render); render(); } }
  if(type==='agency'){ const projects=document.getElementById('projects'); if(projects){ const p=[{title:'App Tracker',seed:'proj1'},{title:'Design System',seed:'proj2'},{title:'E-commerce',seed:'proj3'}]; p.forEach(it=>{ const c=document.createElement('div'); c.className='card'; c.innerHTML=`<img src='https://picsum.photos/seed/${it.seed}/800/420' alt=''><h4>${it.title}</h4>`; projects.appendChild(c); }); } }
  if(type==='florist'){ const bouquet=document.getElementById('bouquetConfig'); if(bouquet){ const flowers=['Róża','Peonia','Eustoma']; const picks=document.createElement('div'); picks.className='small-text'; bouquet.appendChild(picks); const state={}; flowers.forEach(f=>{ const b=document.createElement('button'); b.className='btn'; b.style.margin='0 .4rem .6rem 0'; b.textContent=f; b.addEventListener('click', ()=>{ state[f]=(state[f]||0)+1; picks.textContent=Object.entries(state).map(([k,v])=>`${k} x${v}`).join(' • '); }); bouquet.appendChild(b); }); const reset=document.createElement('button'); reset.className='btn ghost'; reset.textContent='Reset'; reset.addEventListener('click', ()=>{ for(const k in state) delete state[k]; picks.textContent=''; }); bouquet.appendChild(reset); } }
  if(type==='spa'){ const list=document.getElementById('packageList'); if(list){ [{name:'Relax',price:150},{name:'Detox',price:220},{name:'Luxury',price:420}].forEach(p=>{ const d=document.createElement('div'); d.className='card kv'; d.innerHTML=`<div><strong>${p.name}</strong><div class='muted'>${p.price} PLN</div></div>`; const btn=document.createElement('button'); btn.className='btn'; btn.textContent='Rezerwuj'; btn.addEventListener('click', ()=>alert('Zarezerwuj: '+p.name)); d.appendChild(btn); list.appendChild(d); }); } }
  if(type==='logistics'){ const form=document.getElementById('shipForm'); if(form) form.addEventListener('submit', e=>{ e.preventDefault(); const w=parseFloat(document.getElementById('weight').value||0); const d=parseFloat(document.getElementById('distance').value||0); if(!w||!d){ alert('Uzupełnij wagę i dystans'); return; } const base=10, perKg=2.5, perKm=0.3; const cost=Math.max(base,(perKg*w + perKm*d)).toFixed(2); document.getElementById('shipResult').textContent=`Szacowany koszt: ${cost} PLN (symulacja)`; }); }
  if(type==='photography'){ const g=document.getElementById('starlitGallery'); if(g){ for(let i=1;i<=8;i++){ const img=document.createElement('img'); img.src=`https://picsum.photos/seed/starlit${i}/800/520`; g.appendChild(img);} } const form=document.getElementById('starlitBooking'); if(form) form.addEventListener('submit', e=>{ e.preventDefault(); document.getElementById('starlitMsg').textContent='Zapytanie wysłane (symulacja).'; form.reset(); }); }
  if(type==='accounting'){ const taxForm=document.getElementById('taxForm'); if(taxForm) taxForm.addEventListener('submit', e=>{ e.preventDefault(); const inc=parseFloat(document.getElementById('income').value||0); if(!inc){ alert('Wprowadź dochód'); return; } let tax=0; if(inc<=85528) tax=inc*0.17; else tax=85528*0.17 + (inc-85528)*0.32; document.getElementById('taxResult').textContent=`Szacowany podatek: ${tax.toFixed(2)} PLN (symulacja).`; }); }
});